---
title: "Bio 204: Problem Set 05"
output:
  html_document:
    toc: true
    toc_depth: 2
    theme: readable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# <font color = "red">Due Date: 07 November 2016</font>


# Problem 1 

The file [possums.txt](https://github.com/Bio204-class/bio204-datasets/raw/master/possum.txt) is a tab-delimited file that contains morphological measurements on 104 brushtail possums (*Trichosurus vulpecula*). This data set contains information on variables such as sex, age, head length, skull width, tail length, and total body length, as well as information about the population and locality (site) at which each specimen was collected.


## Problem 1a (3 pts)

For the variable `skullW` (skull width) evaluate how well the normal approximation holds by creating a density histogram and correspondingdensity plot (given the sample estimates of the mean and standard deviation).

```
# Problem 1a code

```

## Problem 1b (3 pts)

Create a a normal probability plot showing observed vs theoretical quantiles for the `skullW` variable.

```
# Problem 1b code

```

## Problem 1c (3 pts)?

Calculate the 95% and 99.7% confidence intervals for the mean of the skull width variable.


```
# Problem 1c code

```

# Problem 2

Consider a normal distribution, $\sim N(\mu = 20, \sigma = 2)$.

## Problem 2a (4 pts)

Both the mean and median are measures of location. In this problem you will complare the sampling distributions of these two statistics.

Write R code to simulate the sampling distribution of the **mean** and **median** for random samples of size 10, 25, 50, 100, 200, 400, and 800.  For each sample size, simulate the sampling distribution with 500 random samples and estimate the standard error of each statistic.

```
# Problem 2a code

```

## Problem 2b (4 pts)

Generate a  pair of line plots comparing the standard error of both statistics of interest (mean and median) for the different sample sizes.  

```
# Problem 2b code

```

## Problem 2c (2 pts)

Which of the two statistics, the mean or median, has the smaller standard error?

```
# Problem 2c code

```

